name: train_fivek_expertC_16x16

common:
  seed: 1229
  gpu_id: 0
  deterministic: False

datasets:
  dataset_dir: D:/data/datasets/MIT-Adobe_FiveK/png
  A_dir: input 
  B_dir: expertC_gt
  data_split_file: ./datasets/train_fivek_expertC.pkl
  low_res: [256, 256]

train: 
  lr: 0.0001
  history_size: 50
  total_epochs: 100
  use_scheduler: True
  weight_adversarial: 1.0
  weight_cycle: 10.0
  weight_discriminator: 0.5
  weight_identity: 5.0
  add_identity: True
  train_batch_size: 1

valid:
  repeat: 2
  valid_interval: 1
  valid_batch_size: 1

intermediate:
  save_interval: 1
  checkpoints_dir: "./checkpoints/"
  visualize_batch: 4000
  visualize_dir: "train_phase"
